[package]
name = "lua-interpretter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
thiserror = "1.0.58"
tracing = "0.1.40"
bytes = "1.6.0"